projects:
  sisec:
    schemaPath: amplify/backend/api/sisec/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/services/API.service.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
